// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Alert: typeof import('./components/core/Alert.vue')['default']
    Avatar: typeof import('./components/core/Avatar.vue')['default']
    CodeViewer: typeof import('./components/app/CodeViewer.vue')['default']
    Dialog: typeof import('./components/core/Dialog.vue')['default']
    Drawer: typeof import('./components/core/Drawer.vue')['default']
    Editor: typeof import('./components/app/Editor.vue')['default']
    Header: typeof import('./components/core/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Image: typeof import('./components/core/Image.vue')['default']
    PrismaLogo: typeof import('./components/app/PrismaLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./components/core/SearchInput.vue')['default']
    Select: typeof import('./components/core/Select.vue')['default']
    Snackbar: typeof import('./components/core/Snackbar.vue')['default']
    Spinner: typeof import('./components/core/Spinner.vue')['default']
    StickyHeader: typeof import('./components/core/StickyHeader.vue')['default']
    Switch: typeof import('./components/core/Switch.vue')['default']
    Textarea: typeof import('./components/core/Textarea.vue')['default']
    Textfield: typeof import('./components/core/Textfield.vue')['default']
  }
}
